name: Playwright Tests + Allure + Slack

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Tests
        run: npx playwright test

      - name: Install Allure
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: allure generate allure-results --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # Slack Notification - Success
      - name: Slack Notification (Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Playwright Tests Passed 🎉"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # Slack Notification - Failure
      - name: Slack Notification (Failure)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ Playwright Tests Failed 🚨"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}